image: ubuntu:bionic

build-cli:
  before_script:
    - apt-get -qq update
    - apt-get -qq -y install build-essential cmake
  script:
    - cmake .
    - make -j$(nproc) cppack
  artifacts:
    paths:
      - bin/cppack

build-gui:
  before_script:
    - apt-get -qq update
    - apt-get -qq -y install build-essential qt5-default libqt5charts5-dev cmake
  script:
    - cmake .
    - make -j$(nproc) cppack-gui
  artifacts:
    paths:
      - bin/cppack-gui
