image: ubuntu:18.04
before_script:
  - apt-get -qq update && apt-get -qq -y install build-essential > /dev/null
build:
  script: make -C Statsgen -j2
  artifacts:
    paths:
      - Statsgen/cstatsgen
