image: localhost:5000/stretch
before_script:
  - export http_proxy=http://10.14.128.99:3128
  - apt-get -qq update && apt-get -qq -y install build-essential > /dev/null
build:
  script: make -C Statsgen -j2
  artifacts:
    paths:
      - Statsgen/cstatsgen
