image: matlink/qt5-linux:latest

before_script:
  - apt-get -qq update
  - apt-get -qq -y install build-essential > /dev/null

build-cli:
  script: make -C Statsgen -j$(nproc)
  artifacts:
    paths:
      - Statsgen/cstatsgen

build-gui:
  script:
    - cd GUI
    - qmake
    - make -j$(nproc)
  artifacts:
    paths:
      - GUI/GUI
