image: ubuntu
build-cli:
  before_script:
    - export http_proxy=http://10.14.128.99:3128
    - export https_proxy=http://10.14.128.99:3128
    - apt-get -qq update
    - apt-get -qq -y install build-essential > /dev/null
  script: make -C Statsgen -j2
  artifacts:
    paths:
      - Statsgen/cstatsgen
build-gui:
  before_script:
    - export http_proxy=http://10.14.128.99:3128
    - export https_proxy=http://10.14.128.99:3128
    - apt-get -qq update
    - apt-get -qq -y install build-essential software-properties-common > /dev/null
    - add-apt-repository -y ppa:beineri/opt-qt-5.10.1-xenial
    - apt-get -qq update
    - apt-get -qq -y install qt5-default qt510charts-no-lgpl > /dev/null
    - head -n -5 /opt/qt510/bin/qt510-env.sh > qt510-env.sh
    - mv qt510-env.sh /opt/qt510/bin/qt510-env.sh
    - source /opt/qt510/bin/qt510-env.sh
  script:
    - cd GUI
    - qmake GUI.pro -o makefile
    - make -j$(nproc)
  artifacts:
    paths:
      - GUI/GUI
