image: ubuntu:bionic

build-cli:
  before_script:
    - apt-get -qq update
    - apt-get -qq -y install build-essential
  script: make -j$(nproc) cppack
  artifacts:
    paths:
      - cppack

build-gui:
  before_script:
    - apt-get -qq update
    - apt-get -qq -y install build-essential 
                             qt5-default 
                             libqt5charts5-dev 
                             supervisor 
                             openssh-server
  script: make -j$(nproc) cppack-gui
  artifacts:
    paths:
      - cppack-gui
